import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),esbuildDir=readdirSync('node_modules/.pnpm').find(n=>n.startsWith('esbuild@'));
const {build}=require(`../node_modules/.pnpm/${esbuildDir}/node_modules/esbuild/lib/main.js`);
const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('drizzle/0000_icy_red_hulk.sql','utf8'));
const db={prepare(query){let values=[];return {bind(...params){values=params;return this;},async first(){return sql.prepare(query).get(...values)??null;},async all(){return{results:sql.prepare(query).all(...values)};},run(){return sql.prepare(query).run(...values);}};},async batch(statements){sql.exec('BEGIN IMMEDIATE');try{const results=statements.map(s=>s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
globalThis.__ideaTestEnv={DB:db};globalThis.__ideaTestUser={userId:'alice',email:'alice@example.test'};
async function handlers(entry){const result=await build({entryPoints:[entry],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'isolated-api-test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'cloudflare',namespace:'mock'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'identity',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='cloudflare'?'export const env=globalThis.__ideaTestEnv;':'export async function getChatGPTUser(){return globalThis.__ideaTestUser;}',loader:'js'}));}}]});return import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));}
const world=await handlers('app/api/world/route.ts'),history=await handlers('app/api/history/route.ts');
const object={id:'one',kind:'memo',title:'Untitled',content:'private text',tags:[],archived:false,createdAt:'2026-10-04T00:00:00.000Z',updatedAt:'2026-10-04T00:00:00.000Z'};
const request=(revision,commands,origin='https://grove.example')=>new Request('https://grove.example/api/world',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({revision,commands})});
test('API denies unsigned reads, writes and history',async()=>{const u=globalThis.__ideaTestUser;globalThis.__ideaTestUser=null;assert.equal((await world.GET()).status,401);assert.equal((await world.POST(request(0,[{type:'object.put',object}]))).status,401);assert.equal((await history.GET(new Request('https://grove.example/api/history'))).status,401);globalThis.__ideaTestUser=u;});
test('API persists content and event atomically',async()=>{const r=await world.POST(request(0,[{type:'object.put',object}]));assert.equal(r.status,200);const d=await r.json();assert.equal(d.revision,1);assert.equal(d.world.objects[0].content,'private text');assert.equal(sql.prepare('SELECT count(*) AS n FROM world_events').get().n,1);});
test('another user cannot read data or replay another user history',async()=>{globalThis.__ideaTestUser={userId:'bob',email:'bob@example.test'};const d=await(await world.GET()).json();assert.equal(d.revision,0);assert.equal(d.world.objects.length,0);const h=await(await history.GET(new Request('https://grove.example/api/history'))).json();assert.deepEqual(h.events,[]);assert.equal((await history.GET(new Request('https://grove.example/api/history?revision=1'))).status,404);globalThis.__ideaTestUser={userId:'alice',email:'alice@example.test'};});
test('cross-origin writes and malformed changes are rejected',async()=>{assert.equal((await world.POST(request(1,[{type:'object.delete',id:'one'}],'https://evil.example'))).status,403);assert.equal((await world.POST(request(1,[{type:'invented'}]))).status,400);assert.equal(sql.prepare('SELECT revision FROM worlds WHERE owner_id=?').get('alice').revision,1);});
test('stale revision cannot overwrite saved content',async()=>{const r=await world.POST(request(0,[{type:'object.delete',id:'one'}]));assert.equal(r.status,409);assert.equal(sql.prepare('SELECT count(*) AS n FROM world_events').get().n,1);});
test('simultaneous saves yield one winner without partial history',async()=>{const results=await Promise.all([world.POST(request(1,[{type:'world.rename',name:'A'}])),world.POST(request(1,[{type:'world.rename',name:'B'}]))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal(sql.prepare('SELECT revision FROM worlds WHERE owner_id=?').get('alice').revision,2);assert.equal(sql.prepare('SELECT count(*) AS n FROM world_events').get().n,2);});
test('history reconstructs actual saved past state, including deleted content',async()=>{const r=await world.POST(request(2,[{type:'object.delete',id:'one'}]));assert.equal(r.status,200);const h=await(await history.GET(new Request('https://grove.example/api/history?revision=1'))).json();assert.equal(h.world.objects[0].content,'private text');assert.equal(h.world.name,'私の思考の庭');const d=await(await world.GET()).json();assert.equal(d.world.objects.length,0);assert.equal(d.world.matureCount,1);});
test('saved movement survives reload and past revisions retain their previous positions',async()=>{
 const setup=[{type:'object.put',object:{...object,id:'moving-thought'}},{type:'furniture.put',furniture:{id:'moving-shelf',roomId:'room-0',kind:'shelf',name:'My shelf',x:0,z:0}},{type:'placement.put',placement:{id:'moving-placement',objectId:'moving-thought',furnitureId:'moving-shelf'}},{type:'room.put',room:{id:'moving-house',name:'My house',kind:'house',slots:[],x:25,z:25,color:'#a4b296'}}];
 assert.equal((await world.POST(request(3,setup))).status,200);
 const moved=await world.POST(request(4,[{type:'furniture.move',id:'moving-shelf',x:2,z:-1},{type:'placement.move',id:'moving-placement',position:{u:.4,v:1}},{type:'room.move',id:'moving-house',x:30,z:28}]));assert.equal(moved.status,200);
 const current=await(await world.GET()).json(),past=await(await history.GET(new Request('https://grove.example/api/history?revision=4'))).json();
 assert.equal(current.world.furniture[0].x,2);assert.equal(past.world.furniture[0].x,0);assert.deepEqual(current.world.placements[0].position,{u:.4,v:1});assert.equal(past.world.placements[0].position,undefined);assert.equal(current.world.rooms.find(r=>r.id==='moving-house').x,30);assert.equal(past.world.rooms.find(r=>r.id==='moving-house').x,25);assert.deepEqual(current.world.objects,past.world.objects);
});
