export default function Privacy({hosting = 'cloudflare'}: {hosting?: 'cloudflare' | 'render'}) {
  const render = hosting === 'render';
  return <main style={{height:'100dvh',overflowY:'auto',padding:'48px 24px'}}><article style={{maxWidth:720,margin:'0 auto',lineHeight:1.8}}>
    <a href="/">← Return to Idea Grove</a><h1>Privacy and your data</h1><p>Updated October 6, 2026. This describes the standalone public beta.</p>
    <h2>Your grove is private</h2><p>Signing in with GitHub identifies your account by its stable GitHub ID. We use your public profile name and login for the session. The application does not request your email, repository access or write access to GitHub. An access token is used only to verify sign-in and is then discarded.</p>
    <p>Your thoughts, tags, buildings and placements are stored in {render ? 'Neon PostgreSQL' : 'Cloudflare D1'} under your account ID. The application provides no public sharing. Other users cannot access your grove through its APIs. Hosting administrators have technical access to the database for operation and recovery.</p>
    <h2>History, backups and deletion</h2><p>Growth history retains earlier changes, including thoughts you edit or delete. Export my grove in Settings downloads the current world; it does not include the change history. Delete my grove and history removes both your current world and its history from the live database and signs you out. Export a backup first if you want to keep your data.</p>
    <p>{render ? 'Neon Free recovery history may retain earlier database states for up to six hours. Administrator exports may retain backups for up to seven days; erased accounts are excluded before any restore.' : 'Cloudflare Free point-in-time recovery may retain earlier database states for up to seven days.'} A deletion marker containing the account ID and deletion time is retained so recovery can exclude erased content. It contains no thoughts or profile information. JSON files you downloaded remain under your control.</p>
    <h2>On your device</h2><p>An unsent content draft and weather preferences are stored in your browser per account. They are not encrypted on your device. Sign-in uses secure, HttpOnly cookies: a ten-minute sign-in state and a session lasting up to seven days. Signing out clears the session; local drafts remain available for your next visit. Deleting your grove also clears this account's draft and weather settings on the current device. Other devices and downloaded backups must be cleared separately.</p>
    <h2>Weather and hosting</h2><p>If you choose a location, coordinates rounded to two decimal places are sent through the weather service to Open-Meteo. Device location is requested only after your explicit action. Open-Meteo provides weather model data. GitHub and {render ? 'Render and Neon' : 'Cloudflare'} process authentication and hosting requests under their own policies; network services can receive connection metadata such as an IP address.</p>
    <p>This version contains no advertising or application analytics. {render ? 'Render may retain infrastructure and application logs under its own policies. The application does not log thoughts, sign-in codes, access tokens or database credentials.' : 'Persistent Worker application logs are disabled in the deployment configuration.'} Error responses avoid thoughts and credentials.</p>
    <p><a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub privacy</a> · <>{render ? <><a href="https://render.com/privacy">Render privacy</a> · <a href="https://neon.com/privacy">Neon privacy</a></> : <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare privacy</a>}</> · <a href="https://open-meteo.com/en/terms">Open-Meteo terms</a></p>
    <p><a href="/terms">Public beta terms</a></p>
  </article></main>;
}
