'use client';
import {useEffect,useRef,useState} from 'react';
import {MousePointer2,RotateCcw,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Footprints} from 'lucide-react';
import {drawScene,type Hit} from '../lib/scene';
import {stepWalk,safeSpawn,outdoorSpawn,walkTarget,canStand,type WalkPose,type WalkTarget} from '../lib/walk';
import type {World,Room} from '../lib/domain';
import type {SkyEnvironment} from '../lib/sky';

export default function WalkCanvas({world,room,inspect,highlight,paused,onSelect,onExit,sky}:{world:World;room:Room|null;inspect:boolean;highlight:string|null;paused:boolean;onSelect:(hit:Hit)=>void;onExit:()=>void;sky:SkyEnvironment}){
 const canvas=useRef<HTMLCanvasElement>(null),pose=useRef<WalkPose>(room?safeSpawn(world,room):safeSpawn(world,null)),outside=useRef(outdoorSpawn()),previousRoom=useRef(room?.id??null),keys=useRef(new Set<string>()),drag=useRef<{x:number;y:number}|null>(null),dirty=useRef(true),currentTarget=useRef<WalkTarget|null>(null),actions=useRef({onSelect,onExit});
 const [size,setSize]=useState({w:1000,h:700}),[target,setTarget]=useState<WalkTarget|null>(null),[locked,setLocked]=useState(false),[focused,setFocused]=useState(false);
 actions.current={onSelect,onExit};
 useEffect(()=>{const id=room?.id??null;if(id!==previousRoom.current){if(room){if(previousRoom.current===null)outside.current={...pose.current};pose.current=safeSpawn(world,room,pose.current);}else pose.current=canStand(outside.current.x,outside.current.z,world,null)?{...outside.current}:safeSpawn(world,null);previousRoom.current=id;keys.current.clear();dirty.current=true;}else if(!canStand(pose.current.x,pose.current.z,world,room)){pose.current=safeSpawn(world,room);dirty.current=true;}},[room,world]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const observer=new ResizeObserver(([e])=>setSize({w:e.contentRect.width,h:e.contentRect.height}));observer.observe(el);return()=>observer.disconnect();},[]);
 const interact=()=>{const t=currentTarget.current;if(!t)return;if(t.kind==='exit')actions.current.onExit();else actions.current.onSelect({id:t.id,kind:t.kind,x:0,y:0,radius:0});};
 useEffect(()=>{const el=canvas.current;if(!el)return;const lock=()=>{const enabled=document.pointerLockElement===el;setLocked(enabled);setFocused(document.activeElement===el);keys.current.clear();};const look=(e:MouseEvent)=>{if(document.pointerLockElement!==el||paused)return;pose.current={...pose.current,yaw:pose.current.yaw+e.movementX*.0028,pitch:Math.max(-1.1,Math.min(1.1,pose.current.pitch-e.movementY*.0028))};dirty.current=true;};const down=(e:KeyboardEvent)=>{if(paused||e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift','e'].includes(key)){e.preventDefault();if(key==='e'){if(!e.repeat)interact();return;}keys.current.add(key);}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const clear=()=>{keys.current.clear();drag.current=null;};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);document.addEventListener('pointerlockchange',lock);document.addEventListener('mousemove',look);if(paused){clear();if(document.pointerLockElement===el)document.exitPointerLock();}return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);document.removeEventListener('pointerlockchange',lock);document.removeEventListener('mousemove',look);clear();};},[paused]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const dpr=Math.min(window.devicePixelRatio||1,2);el.width=Math.max(1,size.w*dpr);el.height=Math.max(1,size.h*dpr);const ctx=el.getContext('2d');if(!ctx)return;ctx.scale(dpr,dpr);dirty.current=true;let frame=0,last=0,painted=0,alive=true;
  const tick=(time:number)=>{if(!alive)return;const dt=last?Math.min(.05,(time-last)/1000):0;last=time;const k=keys.current,active=!paused&&(document.activeElement===el||document.pointerLockElement===el||k.has('touch'));
   if(active){const forward=Number(k.has('w')||k.has('arrowup'))-Number(k.has('s')||k.has('arrowdown')),strafe=Number(k.has('d'))-Number(k.has('a')),turn=Number(k.has('arrowright'))-Number(k.has('arrowleft'));if(forward||strafe||turn){pose.current=stepWalk({...pose.current,yaw:pose.current.yaw+turn*dt*1.5},forward,strafe,dt,k.has('shift'),world,room);dirty.current=true;}}
   if(!document.hidden&&(dirty.current||sky.motion&&time-painted>=40)){drawScene(ctx,world,size.w,size.h,{yaw:0,pitch:0,zoom:1},room,inspect,highlight,pose.current,{...sky,now:sky.motion?Date.now():sky.now});const next=walkTarget(pose.current,world,room);if(next?.id!==currentTarget.current?.id||next?.kind!==currentTarget.current?.kind||next?.label!==currentTarget.current?.label)setTarget(next);currentTarget.current=next;dirty.current=false;painted=time;}frame=requestAnimationFrame(tick);
  };frame=requestAnimationFrame(tick);return()=>{alive=false;cancelAnimationFrame(frame);};
 },[world,room,size,inspect,highlight,paused,sky]);
 useEffect(()=>{const el=canvas.current;el?.focus({preventScroll:true});return()=>{if(el&&document.pointerLockElement===el)document.exitPointerLock();};},[]);
 const mouseLook=()=>{const el=canvas.current;if(!el)return;el.focus();try{const request=el.requestPointerLock();if(request)void request.catch(()=>{});}catch{}};
 const reset=()=>{pose.current=safeSpawn(world,room);keys.current.clear();dirty.current=true;canvas.current?.focus();};
 return <><canvas ref={canvas} className="walk-canvas" tabIndex={0} aria-label="First-person view. Click to focus, use WASD to walk, Shift to move faster, drag to look, and E to interact. Arrow keys move and turn. Escape releases mouse look." onFocus={()=>setFocused(true)} onBlur={()=>{setFocused(false);keys.current.clear();}} onPointerDown={e=>{if(paused||e.button!==0)return;e.currentTarget.focus();if(document.pointerLockElement===e.currentTarget)return;drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d||paused)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;pose.current={...pose.current,yaw:pose.current.yaw+dx*.004,pitch:Math.max(-1.1,Math.min(1.1,pose.current.pitch-dy*.004))};drag.current={x:e.clientX,y:e.clientY};dirty.current=true;}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onDoubleClick={mouseLook}/>
  <div className="walk-crosshair" aria-hidden="true"/>
  <div className="walk-hint"><Footprints size={15}/><span>{paused?'Walking paused while editing':!focused&&!locked?'Click the world to start walking':'WASD to walk · Drag to look · Shift to move faster'}</span></div>
  {target&&!paused&&<button className="walk-interaction" onClick={interact}><kbd>E</kbd>{target.label}</button>}
  <div className="walk-tools"><button onClick={mouseLook} title="Lock mouse to look around; Escape releases it"><MousePointer2 size={15}/><span>{locked?'Mouse look · Esc to release':'Mouse look'}</span></button><button onClick={reset} title="Return to entrance" aria-label="Return to entrance"><RotateCcw size={16}/></button></div>
  <div className="walk-touch-controls" aria-label="Walking controls">{([{key:'w',Icon:ArrowUp,label:'Walk forward'},{key:'a',Icon:ArrowLeft,label:'Step left'},{key:'s',Icon:ArrowDown,label:'Walk backward'},{key:'d',Icon:ArrowRight,label:'Step right'}]).map(({key,Icon,label})=><button key={key} aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);keys.current.add(key);keys.current.add('touch');}} onPointerUp={()=>{keys.current.delete(key);keys.current.delete('touch');}} onPointerCancel={()=>keys.current.clear()}><Icon size={17}/></button>)}</div>
 </>;
}
